=== mbta/schemas/schemas/cloudevents.json
{
  "$id": "https://github.com/mbta/schemas/blob/main/schemas/cloudevents.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$comment": "Modified from https://github.com/cloudevents/spec/blob/b43a64bf4fa92baee02dad512f23ea5cb77a321c/cloudevents/formats/cloudevents.json",
  "description": "CloudEvents Specification JSON Schema",
  "type": "object",
  "properties": {
    "id": {
      "description": "Identifies the event.",
      "type": "string",
      "minLength": 1,
      "examples": ["A234-1234-1234"]
    },
    "source": {
      "description": "Identifies the context in which an event happened.",
      "type": "string",
      "format": "uri-reference",
      "minLength": 1,
      "examples": [
        "https://github.com/cloudevents",
        "mailto:cncf-wg-serverless@lists.cncf.io",
        "urn:uuid:6e8bc430-9c3a-11d9-9669-0800200c9a66",
        "cloudevents/spec/pull/123",
        "/sensors/tn-1234567/alerts",
        "1-555-123-4567"
      ]
    },
    "specversion": {
      "description": "The version of the CloudEvents specification which the event uses.",
      "type": "string",
      "minLength": 1,
      "examples": ["1.0"]
    },
    "type": {
      "description": "Describes the type of event related to the originating occurrence.",
      "type": "string",
      "minLength": 1,
      "examples": [
        "com.github.pull_request.opened",
        "com.example.object.deleted.v2"
      ]
    },
    "datacontenttype": {
      "description": "Content type of the data value. Must adhere to RFC 2046 format.",
      "type": ["string", "null"],
      "minLength": 1,
      "examples": [
        "text/xml",
        "application/json",
        "image/png",
        "multipart/form-data"
      ]
    },
    "dataschema": {
      "description": "Identifies the schema that data adheres to.",
      "type": ["string", "null"],
      "format": "uri",
      "minLength": 1
    },
    "subject": {
      "description": "Describes the subject of the event in the context of the event producer (identified by source).",
      "type": ["string", "null"],
      "minLength": 1,
      "examples": ["mynewfile.jpg"]
    },
    "time": {
      "description": "Timestamp of when the occurrence happened. Must adhere to RFC 3339.",
      "type": ["string", "null"],
      "format": "date-time",
      "minLength": 1,
      "examples": ["2018-04-05T17:31:00Z"]
    },
    "data": {
      "description": "The event payload.",
      "anyOf": [
        { "type": "object" },
        { "type": "string" },
        { "type": "number" },
        { "type": "array" },
        { "type": "boolean" },
        { "type": "null" }
      ],
      "examples": ["<much wow=\"xml\"/>"]
    },
    "data_base64": {
      "description": "Base64 encoded event payload. Must adhere to RFC4648.",
      "type": ["string", "null"],
      "contentEncoding": "base64",
      "examples": ["Zm9vYg=="]
    }
  },
  "required": ["id", "source", "specversion", "type"]
}

=== mbta/schemas/examples/com.mbta.railds/com.mbta.railds.io.frame.v1.example.json
{
  "specversion": "1.0",
  "type": "com.mbta.railds.io.frame.v1",
  "source": "/edge-collector/EDGE-001",
  "id": "5bc95463-86fe-4e63-8aa8-385d90d38e10",
  "time": "2026-07-24T15:00:02.375Z",
  "datacontenttype": "application/json",
  "data": {
    "asset_id": "SITE-001",
    "acquired_utc": "2026-07-24T15:00:02.375Z",
    "sample_interval_sec": 0.08,
    "io_device": {
      "device_id": "IO-DEVICE-001",
      "device_type": "moxa"
    },
    "modules": [
      {
        "slot": 1,
        "module": {
          "model": "45MR-3810",
          "read_ok": true,
          "error": null,
          "read_elapsed_ms": 0.42
        },
        "channels": [
          {
            "channel": 0,
            "configured": true,
            "raw_value": 12.0,
            "raw_format": "mA",
            "scaled_value": 75.0,
            "scaled_format": "Volts",
            "monitoring_target_type": "switch",
            "monitoring_target_name": "SWITCH-001",
            "monitoring_target_circuit": "NORMAL",
            "monitoring_target_description": "Normal line voltage"
          },
          {
            "channel": 1,
            "configured": true,
            "raw_value": 4.0,
            "raw_format": "mA",
            "scaled_value": 0.0,
            "scaled_format": "Volts",
            "monitoring_target_type": "switch",
            "monitoring_target_name": "SWITCH-001",
            "monitoring_target_circuit": "REVERSE",
            "monitoring_target_description": "Reverse line voltage"
          }
        ]
      },
      {
        "slot": 2,
        "module": {
          "model": "45MR-3800",
          "read_ok": true,
          "error": null,
          "read_elapsed_ms": 0.35
        },
        "channels": [
          {
            "channel": 0,
            "configured": true,
            "raw_value": 8.8,
            "raw_format": "mA",
            "scaled_value": 9.0,
            "scaled_format": "Amps",
            "monitoring_target_type": "switch",
            "monitoring_target_name": "SWITCH-001",
            "monitoring_target_circuit": "NORMAL",
            "monitoring_target_description": "Normal motor current"
          },
          {
            "channel": 1,
            "configured": false,
            "raw_value": 4.0,
            "raw_format": "mA"
          }
        ]
      },
      {
        "slot": 3,
        "module": {
          "model": "45MR-1600",
          "read_ok": true,
          "error": null,
          "read_elapsed_ms": 0.31
        },
        "channels": [
          {
            "channel": 0,
            "configured": true,
            "raw_value": 0,
            "raw_format": "Boolean",
            "monitoring_target_type": "alarm",
            "monitoring_target_name": "POWER-SUPPLY-001",
            "monitoring_target_description": "Power supply alarm"
          },
          {
            "channel": 1,
            "configured": true,
            "raw_value": 1,
            "raw_format": "Boolean",
            "monitoring_target_type": "indication",
            "monitoring_target_name": "ENCLOSURE-DOOR-001",
            "monitoring_target_description": "Door closed indication"
          }
        ]
      }
    ]
  }
}

=== mbta/schemas/examples/glides-events/vehicle_trip_assignments.v1.json
[
  {
    "type": "com.mbta.ctd.glides.vehicle_trip_assignments.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2024-11-14T09:50:00-04:00",
    "data": {
      "assignments": [
        {
          "vehicle": {
            "vehicleId": "G-12345",
            "carNumbers": ["3901", "3902"]
          },
          "tripKey": null
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.vehicle_trip_assignments.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2024-11-14T10:00:00-04:00",
    "data": {
      "assignments": [
        {
          "vehicle": {
            "vehicleId": "G-12345",
            "carNumbers": ["3901", "3902"]
          },
          "tripKey": {
            "serviceDate": "2024-11-14",
            "tripId": "11111111",
            "scheduled": "scheduled",
            "revenue": "revenue"
          }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.vehicle_trip_assignments.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2024-11-14T10:55:00-04:00",
    "data": {
      "assignments": [
        {
          "vehicle": {
            "vehicleId": "G-12345",
            "carNumbers": ["3901", "3902"]
          },
          "tripKey": {
            "serviceDate": "2024-11-14",
            "tripId": "22222222",
            "scheduled": "scheduled",
            "revenue": "revenue"
          }
        },
        {
          "vehicle": null,
          "tripKey": {
            "serviceDate": "2024-11-14",
            "tripId": "11111111",
            "scheduled": "scheduled",
            "revenue": "revenue"
          }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.vehicle_trip_assignments.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2024-11-14T11:02:00-04:00",
    "data": {
      "assignments": [
        {
          "vehicle": {
            "vehicleId": "G-12345",
            "carNumbers": ["3902", "3901"]
          },
          "tripKey": {
            "serviceDate": "2024-11-14",
            "tripId": "22222222",
            "scheduled": "scheduled",
            "revenue": "revenue"
          }
        }
      ]
    }
  },
  {
    "type": "com.mbta.ctd.glides.vehicle_trip_assignments.v1",
    "specversion": "1.0",
    "source": "glides.mbta.com",
    "id": "19fdb184-7dd6-4664-8472-04bd6177ec44",
    "time": "2024-11-14T11:55:00-04:00",
    "data": {
      "assignments": [
        {
          "vehicle": {
            "vehicleId": "G-12345",
            "carNumbers": null
          },
          "tripKey": null
        },
        {
          "vehicle": null,
          "tripKey": {
            "serviceDate": "2024-11-14",
            "tripId": "22222222",
            "scheduled": "scheduled",
            "revenue": "revenue"
          }
        }
      ]
    }
  }
]

=== mbta/schemas/examples/com.mbta.railds/com.mbta.railds.control-system.variables.v1.changes-only.json
{
  "specversion": "1.0",
  "type": "com.mbta.railds.control-system.variables.v1",
  "source": "/edge-collector/EDGE-001",
  "id": "bd29a997-89d8-44a5-b927-7456e457a006",
  "subject": "control-system/CONTROL-SYSTEM-001/variables/changes-only",
  "time": "2026-07-24T15:00:00.125Z",
  "datacontenttype": "application/json",
  "data": {
    "asset_id": "ASSET-001",
    "data_scope": "changes_only",
    "control_system": {
      "type": "microlok",
      "name": "CONTROL-SYSTEM-001",
      "connection": {
        "type": "serial",
        "id": "serial-port-1"
      },
      "mode": "Active"
    },
    "control_system_event_time": "2026-07-24T11:00:00.500",
    "state_scope": "partial",
    "variable_states": [
      {
        "index": 1001,
        "name": "CLOCK.SECOND",
        "old_value": 58,
        "value": 59,
        "data_type": "number"
      },
      {
        "index": 1001,
        "name": "CLOCK.SECOND",
        "old_value": 59,
        "value": 0,
        "data_type": "number"
      },
      {
        "index": 201,
        "name": "EXAMPLE.SWITCH.NORMAL.INDICATION",
        "old_value": 0,
        "value": 1,
        "data_type": "boolean"
      }
    ]
  }
}

=== mbta/schemas/examples/com.mbta.railds/com.mbta.railds.control-system.variables.v1.full-state.json
{
  "specversion": "1.0",
  "type": "com.mbta.railds.control-system.variables.v1",
  "source": "/edge-collector/EDGE-001",
  "id": "6db157f8-87de-4df8-bc45-428be2c8d88d",
  "subject": "control-system/CONTROL-SYSTEM-001/variables/full-state",
  "time": "2026-07-24T15:00:01.250Z",
  "datacontenttype": "application/json",
  "data": {
    "asset_id": "ASSET-001",
    "data_scope": "full_state",
    "control_system": {
      "type": "microlok",
      "name": "CONTROL-SYSTEM-001",
      "connection": {
        "type": "serial",
        "id": "serial-port-1"
      },
      "mode": "Active"
    },
    "state_scope": "full",
    "variable_states": [
      {
        "index": 1,
        "name": "SYSTEM.READY",
        "value": 1,
        "data_type": "boolean"
      },
      {
        "index": 201,
        "name": "EXAMPLE.SWITCH.NORMAL.INDICATION",
        "value": 1,
        "data_type": "boolean"
      },
      {
        "index": 202,
        "name": "EXAMPLE.SWITCH.REVERSE.INDICATION",
        "value": 0,
        "data_type": "boolean"
      },
      {
        "index": 203,
        "name": "EXAMPLE.SWITCH.NORMAL.COMMAND",
        "value": 1,
        "data_type": "boolean"
      },
      {
        "index": 204,
        "name": "EXAMPLE.SWITCH.REVERSE.COMMAND",
        "value": 0,
        "data_type": "boolean"
      },
      {
        "index": 1001,
        "name": "CLOCK.SECOND",
        "value": 0,
        "data_type": "number"
      },
      {
        "index": 1002,
        "name": "SYSTEM.LOAD",
        "value": 37,
        "data_type": "number"
      },
      {
        "index": 1003,
        "name": "APPLICATION.VERSION",
        "value": 1,
        "data_type": "number"
      }
    ]
  }
}
